version: '1.0.0'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev
    container_name: keycloak_22.0.1
    restart: always
    ports:
      - "18080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin