version: '1.0.0'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql_8.0.33
    restart: always
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/logs